### ISSUE TITLE
식당검색 API 개발

### ISSUE THREAD

**Issue by peachea27** [yhs99/gt-team-pj#33]
### 📄 Describe

-식당 정보 검색: 식당 목록 조회 
-필터링을 통한 검색: 식당 목록 필터링 조회
-식당 상세 정보: 특정 식당 상세 정보

### ✅ Tasks

- [ ] 식당 정보 검색
- [ ] 필터링을 통한 검색
- [ ] 식당 상세 정보
