### ISSUE TITLE
예약 확인 API 개발

### ISSUE THREAD

**Issue by peachea27** [yhs99/gt-team-pj#43]
### 📄 Describe

-예약 상태 확인: 해당 예약건의 예약 상태 확인 
-예약 가능 여부 확인: 해당 날짜/시간에 해당 식당의 예약 가능 여부
-예약 완료 알림(관리자): 예약 완료시 이메일/SMS로 예약 완료 알림 전송 

### ✅ Tasks

- [x] 예약 상태 확인
- [x] 예약 가능 여부 확인
- [x] 예약 완료 알림(관리자)
