### ISSUE TITLE
예약 관리(관리자) API 개발

### ISSUE THREAD

**Issue by peachea27** [yhs99/gt-team-pj#47]
### 📄 Describe

-전체 예약 내역 조회: 모든 식당의 예약 내역 조회
-특정 식당 예약 내역 조회: 특정 식당의 예약 내역 조회
-예약 상태 수정 : 예약 상태 수정
-예약 삭제 

### ✅ Tasks

- [ ] 전체 예약 내역 조회
- [ ] 특정 식당 예약 내역 조회
- [ ] 예약 상태 수정
- [ ] 예약 삭제
